import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" flex justify-center bg-slate-900 min-h-screen">
          <div className="flex flex-col w-full max-w-7xl">
            <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
